-- --------  << terapiaintegrativa >>  ----------
--
--                    SCRIPT DE CRIACAO (DDL)
--
-- Data Criacao ...........: 31/08/2022
-- Autor(es) ..............: Antonio Rangel Chaves - 180098021, Davi Lima da Silva - 190026588
-- Banco de Dados .........: MySQL 8.0
-- Base de Dados (nome) ...: terapiaintegrativa
--
-- PROJETO => 01 Base de Dados
--         => 29 Tabelas
-- ---------------------------------------------------------
-- BASE DE DADOS
CREATE DATABASE IF NOT EXISTS terapiaintegrativa;
USE terapiaintegrativa;
-- TABELAS
CREATE TABLE PESSOA (
    cpf BIGINT NOT NULL,
    cep INT NOT NULL,
    cidade VARCHAR(30) NOT NULL,
    complemento VARCHAR(100),
    rua VARCHAR(50) NOT NULL,
    numero INT NOT NULL,
    bairro VARCHAR(50) NOT NULL,
    dtNascimento DATE NOT NULL,
    nome VARCHAR(100) NOT NULL,
    sexo ENUM('M', 'F') NOT NULL,
    rg INT NOT NULL,
    
 CONSTRAINT PESSOA_PK PRIMARY KEY(cpf),
 
 CONSTRAINT PESSOA_cep_UK UNIQUE KEY(cep),
 
 CONSTRAINT PESSOA_rg_UK UNIQUE KEY(cep)
)ENGINE = InnoDB;

CREATE TABLE LOJA (
    idLoja INT NOT NULL AUTO_INCREMENT,
    cep INT NOT NULL,
    numero INT NOT NULL,
    bairro VARCHAR(30) NOT NULL,
    cidade VARCHAR(30) NOT NULL,
    rua VARCHAR(50) NOT NULL,
    complemento VARCHAR(100),
    nomeLoja VARCHAR(50) NOT NULL,
    
CONSTRAINT LOJA_PK PRIMARY KEY(idLoja),

CONSTRAINT LOJA_cep_UK UNIQUE KEY(cep)
 
)ENGINE = InnoDB AUTO_INCREMENT = 1;

CREATE TABLE PRODUTO (
    idProduto INT NOT NULL AUTO_INCREMENT,
    precoCompra DECIMAL(8,2) NOT NULL,
    precoVenda DECIMAL(8,2) NOT NULL,
    nomeProduto VARCHAR(40) NOT NULL,
    saldoEstoque INT NOT NULL,
    volume INT,
    tipoConsistencia VARCHAR(30),
    posologia VARCHAR(200),
    
 CONSTRAINT PRODUTO_PK PRIMARY KEY(idProduto)
)ENGINE = InnoDB AUTO_INCREMENT = 1;


CREATE TABLE CURSO (
    idCurso INT NOT NULL AUTO_INCREMENT,
    nomeCurso VARCHAR(50) NOT NULL,
    dtInicio DATE NOT NULL,
    dtFim DATE NOT NULL,
    numRegistro INT NOT NULL,
    
 CONSTRAINT CURSO_PK PRIMARY KEY(idCurso)
)ENGINE = InnoDB AUTO_INCREMENT = 1;


CREATE TABLE TURMA (
    idTurma INT NOT NULL AUTO_INCREMENT,
    idCurso INT NOT NULL,
    
 CONSTRAINT TURMA_PK PRIMARY KEY(idTurma),
 CONSTRAINT TURMA_CURSO_FK FOREIGN KEY(idCurso)
	REFERENCES CURSO(idCurso)
)ENGINE = InnoDB AUTO_INCREMENT = 1;



CREATE TABLE RECEITA (
    idReceita INT NOT NULL AUTO_INCREMENT,
    fase INT NOT NULL,
    
 CONSTRAINT RECEITA_PK PRIMARY KEY(idReceita)
)ENGINE = InnoDB AUTO_INCREMENT = 1;

CREATE TABLE ALUNO (
    matricula INT NOT NULL AUTO_INCREMENT,
    cpf BIGINT NOT NULL,
    idTurma INT NOT NULL,
    
    
 CONSTRAINT ALUNO_PK PRIMARY KEY(matricula),
 CONSTRAINT ALUNO_PESSOA_FK FOREIGN KEY(cpf)
	REFERENCES PESSOA(cpf),
 CONSTRAINT ALUNO_TURMA_FK FOREIGN KEY(idTurma)
	REFERENCES TURMA(idTurma)
)ENGINE = InnoDB AUTO_INCREMENT = 1;

CREATE TABLE TERAPEUTA (
    numRegistro INT NOT NULL,
    especialidade VARCHAR(40) NOT NULL,
    cpf BIGINT NOT NULL,
    
 CONSTRAINT TERAPEUTA_PK PRIMARY KEY(numRegistro),
 CONSTRAINT TERAPEUTA_PESSOA_FK FOREIGN KEY(cpf)
	REFERENCES PESSOA(cpf)
)ENGINE = InnoDB;

CREATE TABLE TELEFONE (
    idTelefone INT NOT NULL AUTO_INCREMENT,
    ddd INT NOT NULL,
    numTelefone INT NOT NULL,
    UNIQUE (ddd, numTelefone),
    
CONSTRAINT TELEFONE_PK PRIMARY KEY(idTelefone),

CONSTRAINT TELEFONE_ddd_numTelefone_UK UNIQUE KEY(ddd, numTelefone)
)ENGINE = InnoDB AUTO_INCREMENT = 1;

CREATE TABLE FICHADESINTOX (
    idFichaDesintox INT NOT NULL AUTO_INCREMENT,
    idConsulta INT NOT NULL,
    
 CONSTRAINT FICHADESINTOX_PK PRIMARY KEY(idFichaDesintox)
)ENGINE = InnoDB AUTO_INCREMENT = 1;

CREATE TABLE PACIENTE (
    idPaciente INT NOT NULL AUTO_INCREMENT,
    profissao VARCHAR(40) NOT NULL,
    tipoSanguineo ENUM('A+','B+','AB+','O+','A-','B-','AB-','O-') NOT NULL,
    queixaPrincipal VARCHAR(500) NOT NULL,
    estadoCivil ENUM('solteiro(a)', 'casado(a)', 'separado(a)', 'divorciado(a)', 'viúvo(a)') NOT NULL,
    email VARCHAR(256) NOT NULL,
    cpf BIGINT NOT NULL,
    
 CONSTRAINT PACIENTE_PK PRIMARY KEY(idPaciente),
 CONSTRAINT PACIENTE_PESSOA_FK FOREIGN KEY(cpf)
	REFERENCES PESSOA(cpf)
)ENGINE = InnoDB AUTO_INCREMENT = 1;

CREATE TABLE CONSULTORIO (
    idConsultorio INT NOT NULL,
    nomeConsultorio VARCHAR(50) NOT NULL,
    rua VARCHAR(50) NOT NULL,
    bairro VARCHAR(50) NOT NULL,
    numero INT NOT NULL,
    cep INT UNIQUE NOT NULL,
    cidade VARCHAR(100) NOT NULL,
    complemento VARCHAR(200),

 CONSTRAINT CONSULTORIO_PK PRIMARY KEY(idConsultorio)
)ENGINE = InnoDB AUTO_INCREMENT = 1;

CREATE TABLE SESSAO (
    idSessao INT NOT NULL AUTO_INCREMENT,
    dtSessao DATE NOT NULL,
    precoUnitarioSessao DECIMAL(8,2) NOT NULL,
    numRegistro INT NOT NULL,
    idFichaDesintox INT NOT NULL,
    idPaciente INT NOT NULL,
    
 CONSTRAINT SESSAO_PK PRIMARY KEY(idSessao),
 
 CONSTRAINT SESSAO_TERAPEUTA_FK FOREIGN KEY(numRegistro)
	REFERENCES TERAPEUTA(numRegistro),
    
 CONSTRAINT SESSAO_FICHADESINTOX_FK FOREIGN KEY(idFichaDesintox)
	REFERENCES FICHADESINTOX(idFichaDesintox),
    
 CONSTRAINT SESSAO_PACIENTE_FK FOREIGN KEY(idPaciente)
	REFERENCES PACIENTE(idPaciente)
)ENGINE = InnoDB AUTO_INCREMENT = 1;

CREATE TABLE CONSULTA (
    idConsulta INT NOT NULL AUTO_INCREMENT,
    dtConsulta DATE NOT NULL,
    
 CONSTRAINT CONSULTA_PK PRIMARY KEY(idConsulta)
)ENGINE = InnoDB AUTO_INCREMENT = 1;

CREATE TABLE ORGAO (
	idTesteEPI INT NOT NULL,
    nomeOrgao VARCHAR(30) NOT NULL
    
)ENGINE = InnoDB;

CREATE TABLE TESTEEPIGENETICO (
    idTesteEPI INT NOT NULL AUTO_INCREMENT,
    dtTesteEPI DATE NOT NULL,
    
 CONSTRAINT TESTEEPIGENETICO_PK PRIMARY KEY(idTesteEPI)
)ENGINE = InnoDB AUTO_INCREMENT = 1;

CREATE TABLE TESTEORTOBIOMOLECULAR (
    idTesteOBM INT NOT NULL AUTO_INCREMENT,
    dtTesteOBM DATE NOT NULL,
    descricaoTesteOBM VARCHAR(600) NOT NULL,
    
 CONSTRAINT TESTEORTOBIOMOLECULAR_PK PRIMARY KEY(idTesteOBM)
)ENGINE = InnoDB AUTO_INCREMENT = 1;

CREATE TABLE QUESTAO (
    idQuestao INT NOT NULL AUTO_INCREMENT,
    enunciado VARCHAR(40) NOT NULL,
    respostaEnun ENUM('Sim' ,'Não') NOT NULL,
    observacao VARCHAR(80) NOT NULL,
    idTesteOBM INT NOT NULL,
    
 CONSTRAINT QUESTAO_PK PRIMARY KEY(idQuestao),
 
 CONSTRAINT QUESTAO_TESTEORTOBIOMOLECULAR_FK FOREIGN KEY(idTesteOBM)
	REFERENCES TESTEORTOBIOMOLECULAR(idTesteOBM)
)ENGINE = InnoDB AUTO_INCREMENT = 1;

CREATE TABLE RESULTADOTESTE (
    idResultadoTeste INT NOT NULL AUTO_INCREMENT,
    predisposicao VARCHAR(50) NOT NULL,
    verificarProxSessao ENUM('Sim', 'Não') NOT NULL,
    idTesteEPI INT NOT NULL,
    
 CONSTRAINT RESULTADOTESTE_PK PRIMARY KEY(idResultadoTeste),
 
 CONSTRAINT RESULTADOTESTE_TESTEEPIGENETICO_FK FOREIGN KEY(idTesteEPI)
	REFERENCES TESTEEPIGENETICO(idTesteEPI)
)ENGINE = InnoDB AUTO_INCREMENT = 1;

CREATE TABLE ORIENTACAORECEITA (
    idOrientacaoRec INT NOT NULL AUTO_INCREMENT,
    orientacao VARCHAR(50) NOT NULL,
    idResultadoTeste INT NOT NULL,
    
 CONSTRAINT ORIENTACAORECEITA_PK PRIMARY KEY(idOrientacaoRec),
 
 CONSTRAINT ORIENTACAORECEITA_RESULTADOTESTE_FK FOREIGN KEY(idResultadoTeste)
	REFERENCES RESULTADOTESTE(idResultadoTeste)
)ENGINE = InnoDB AUTO_INCREMENT = 1;

CREATE TABLE VENDA (
    idVenda INT NOT NULL AUTO_INCREMENT,
    idLoja INT NOT NULL,
    idProduto INT NOT NULL,
    dataVenda DATE NOT NULL,
    numRegistro INT NOT NULL,
    
 CONSTRAINT VENDA_PK PRIMARY KEY(idVenda),
 
 CONSTRAINT VENDA_LOJA_FK FOREIGN KEY(idLoja)
	REFERENCES LOJA(idLoja),
    
 CONSTRAINT VENDA_PRODUTO_FK FOREIGN KEY(idProduto)
	REFERENCES PRODUTO(idProduto),
    
 CONSTRAINT VENDA_TERAPEUTA_FK FOREIGN KEY(numRegistro)
	REFERENCES TERAPEUTA(numRegistro)
)ENGINE = InnoDB AUTO_INCREMENT = 1;

CREATE TABLE estoca (
    idEstoque INT NOT NULL,
    idProduto INT NOT NULL,
    
 CONSTRAINT estoca_ESTOQUE_FK FOREIGN KEY(idEstoque)
	REFERENCES ESTOQUE(idEstoque),
    
 CONSTRAINT estoca_PRODUTO_FK FOREIGN KEY(idProduto)
	REFERENCES PRODUTO(idProduto)
    
)ENGINE = InnoDB;

CREATE TABLE pertence (
    cpf INT NOT NULL,
    idTelefone INT NOT NULL,
    
 CONSTRAINT pertence_PESSOA_FK FOREIGN KEY(cpf)
	REFERENCES PESSOA(cpf),
    
 CONSTRAINT pertence_TELEFONE_FK FOREIGN KEY(idTelefone)
	REFERENCES TELEFONE(idTelefone)
)ENGINE = InnoDB;

CREATE TABLE contem (
    idReceita INT NOT NULL,
    idProduto INT NOT NULL,
    
 CONSTRAINT contem_RECEITA_FK FOREIGN KEY(idReceita)
	REFERENCES RECEITA(idReceita),
    
 CONSTRAINT contem_PRODUTO_FK FOREIGN KEY(idProduto)
	REFERENCES PRODUTO(idProduto)
)ENGINE = InnoDB;

CREATE TABLE gera (
    idSessao INT NOT NULL,
    idReceita INT NOT NULL,
    
 CONSTRAINT gera_SESSAO_FK FOREIGN KEY(idSessao)
	REFERENCES SESSAO(idSessao),
    
 CONSTRAINT gera_RECEITA_FK FOREIGN KEY(idReceita)
	REFERENCES RECEITA(idReceita)
)ENGINE = InnoDB;


CREATE TABLE DEDUCAOTESTEOBM (
    deducaoTesteOBM VARCHAR(60) NOT NULL,
    idTesteOBM INT NOT NULL,
    
 CONSTRAINT DEDUCAOTESTEOBM_TESTEORTOBIOMOLECULAR_FK FOREIGN KEY(idTesteOBM)
	REFERENCES TESTEORTOBIOMOLECULAR(idTesteOBM)
)ENGINE = InnoDB;

CREATE TABLE atende (
    numRegistro INT NOT NULL,
    idPaciente INT NOT NULL,
    
 CONSTRAINT atende_TERAPEUTA_FK FOREIGN KEY(numRegistro)
	REFERENCES TERAPEUTA(numRegistro),
    
 CONSTRAINT atende_PACIENTE_FK FOREIGN KEY(idPaciente)
	REFERENCES PACIENTE(idPaciente)
)ENGINE = InnoDB;

CREATE TABLE ESTOQUE (
    idEstoque INT KEY NOT NULL AUTO_INCREMENT,
    saldoMonetario DECIMAL(8,2) NOT NULL,
    idLoja INT NOT NULL,
    
 CONSTRAINT ESTOQUE_PK PRIMARY KEY(idEstoque),
 
 CONSTRAINT ESTOQUE_LOJA_FK FOREIGN KEY(idLoja)
	REFERENCES LOJA(idLoja)
)ENGINE = InnoDB AUTO_INCREMENT = 1;

CREATE TABLE PAGAMENTO (
    idPagamento INT NOT NULL AUTO_INCREMENT,
    valorMonetario DECIMAL(8,2) NOT NULL,
    dtPagamento DATE NOT NULL,
    metodoPagamento ENUM('Cartão débito', 'Cartão crédito', 'Transferência bancária') NOT NULL,
    servico ENUM('Consulta', 'Sessão de tratamento', 'Curso de terapeuta' ,'Produto') NOT NULL,
    idVenda INT UNIQUE NOT NULL,
    
 CONSTRAINT PAGAMENTO_PK PRIMARY KEY(idPagamento),
 
 CONSTRAINT PAGAMENTO_VENDA_FK FOREIGN KEY(idVenda)
	REFERENCES VENDA(idVenda)
)ENGINE = InnoDB AUTO_INCREMENT = 1;

CREATE TABLE vende (
    idVenda INT NOT NULL,
    idProduto INT NOT NULL,
    
 CONSTRAINT vende_VENDA_FK FOREIGN KEY(idVenda)
	REFERENCES VENDA(idVenda),
    
 CONSTRAINT vende_PRODUTO_FK FOREIGN KEY(idProduto)
	REFERENCES PRODUTO(idProduto)
)ENGINE = InnoDB;

CREATE TABLE vincula (
    idConsultorio INT NOT NULL,
    idTerapeuta INT NOT NULL,
    
 CONSTRAINT vincula_CONSULTORIO_FK FOREIGN KEY(idConsultorio)
	REFERENCES CONSULTORIO(idConsultorio),
    
 CONSTRAINT vincula_TERAPEUTA_FK FOREIGN KEY(idTerapeuta)
	REFERENCES TERAPEUTA(idTerapeuta)
)ENGINE = InnoDB;
 
